[project]
name = "baxter"
version = "0.1.0"
description = "An event-driven backtester for quantitative trading strategies."
readme = "README.md"
authors = [
    { name = "Nicolai Banke", email = "nicolaibanke@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.3",
    "pandas>=3.0.0",
    "pandera>=0.30.1",
]

[project.scripts]
baxter = "baxter.main:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "hypothesis>=6.150.2",
    "pandera[mypy]>=0.30.1",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "ruff>=0.15.9",
    "ty>=0.0.29",
]

[tool.ruff.format]
skip-magic-trailing-comma = false

[tool.mypy]
plugins = "pandera.mypy"

[[tool.ty.overrides]]
include=["src/baxter/execution/saxo.py", "src/baxter/main.py"]
[tool.ty.overrides.rules]
missing-typed-dict-key = "ignore"
